disabled_rules:
- trailing_newline
- vertical_whitespace
- trailing_whitespace
- identifier_name
- type_name
- legacy_constructor
- multiple_closures_with_trailing_closure
excluded:
- Pods/
- Podfile
- Podfile.lock
- R.generated.swift

# 1行の文字数が200超えると警告、300超えるとエラーにする
line_length:
- 200 # warning
- 300 # error
