# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Github-API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Github-API

  pod 'R.swift'
  pod 'Nuke', '~> 9.0'
  pod 'LicensePlist'
  pod 'SwiftLint'

pod 'DZNEmptyDataSet'

  target 'Github-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Github-APIUITests' do
    # Pods for testing
  end

end
